import type { INodeProperties } from 'n8n-workflow';

import { createStringListField, showFor } from '../../shared/descriptions';

const sendOperations = [
  'sendText',
  'sendImage',
  'sendVideo',
  'sendDocument',
  'sendAudio',
  'sendSticker',
  'sendContact',
  'sendLocation',
  'sendPoll',
];

export const messageDescription: INodeProperties[] = [
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: showFor('message'),
    options: [
      {
        name: 'Decrypt Webhook Media',
        value: 'decryptMedia',
        action: 'Decrypt incoming webhook media payload to n8n binary file',
      },
      { name: 'Delete Message', value: 'delete', action: 'Delete revoke sent message' },
      { name: 'Edit Message', value: 'edit', action: 'Edit sent message' },
      { name: 'Get Message Info', value: 'getInfo', action: 'Get message delivery info' },
      { name: 'Mark as Read', value: 'markAsRead', action: 'Mark message as read blue ticks' },
      { name: 'Resend Message', value: 'resend', action: 'Resend failed message' },
      { name: 'Send Audio', value: 'sendAudio', action: 'Send audio message or voice note' },
      { name: 'Send Contact', value: 'sendContact', action: 'Send contact v card' },
      { name: 'Send Document', value: 'sendDocument', action: 'Send document or file attachment' },
      { name: 'Send Image', value: 'sendImage', action: 'Send image message' },
      { name: 'Send Location', value: 'sendLocation', action: 'Send GPS location' },
      { name: 'Send Poll', value: 'sendPoll', action: 'Send interactive poll' },
      { name: 'Send Sticker', value: 'sendSticker', action: 'Send sticker' },
      { name: 'Send Text', value: 'sendText', action: 'Send text message' },
      { name: 'Send Video', value: 'sendVideo', action: 'Send video message' },
    ],
    default: 'sendText',
  },
  {
    displayName: 'Recipient',
    name: 'to',
    type: 'string',
    default: '',
    required: true,
    displayOptions: showFor('message', sendOperations),
    placeholder: '1234567890 or 1234567890@s.whatsapp.net / group-ID@g.us',
    description: 'WhatsApp recipient phone number or full chat/group JID',
  },
  {
    displayName: 'Message Text',
    name: 'text',
    type: 'string',
    typeOptions: { rows: 4 },
    default: '',
    required: true,
    displayOptions: showFor('message', ['sendText']),
    description: 'The text message content to send (supports emojis and markdown)',
  },
  {
    displayName: 'Image URL',
    name: 'imageUrl',
    type: 'string',
    default: '',
    required: true,
    displayOptions: showFor('message', ['sendImage']),
    description: 'Publicly accessible URL of the image to send',
  },
  {
    displayName: 'Video URL',
    name: 'videoUrl',
    type: 'string',
    default: '',
    required: true,
    displayOptions: showFor('message', ['sendVideo']),
    description: 'Publicly accessible URL of the video to send',
  },
  {
    displayName: 'Audio URL',
    name: 'audioUrl',
    type: 'string',
    default: '',
    required: true,
    displayOptions: showFor('message', ['sendAudio']),
    description: 'Publicly accessible URL of the audio file to send',
  },
  {
    displayName: 'Voice Note (PTT)',
    name: 'ptt',
    type: 'boolean',
    default: false,
    displayOptions: showFor('message', ['sendAudio']),
    description: 'Whether to send as a push-to-talk voice note with waveform',
  },
  {
    displayName: 'Document URL',
    name: 'documentUrl',
    type: 'string',
    default: '',
    required: true,
    displayOptions: showFor('message', ['sendDocument']),
    description: 'Publicly accessible URL of the document file to send',
  },
  {
    displayName: 'File Name',
    name: 'fileName',
    type: 'string',
    default: '',
    displayOptions: showFor('message', ['sendDocument']),
    description: 'Original file name including extension (e.g. invoice.pdf)',
  },
  {
    displayName: 'MIME Type',
    name: 'mimeType',
    type: 'string',
    default: '',
    displayOptions: showFor('message', ['sendDocument', 'sendAudio', 'sendImage', 'sendVideo', 'sendSticker']),
    description: 'Optional explicit MIME type (e.g. application/pdf, audio/ogg)',
  },
  {
    displayName: 'Sticker URL',
    name: 'stickerUrl',
    type: 'string',
    default: '',
    required: true,
    displayOptions: showFor('message', ['sendSticker']),
    description: 'Publicly accessible URL of the WebP sticker image to send',
  },
  {
    displayName: 'Caption',
    name: 'caption',
    type: 'string',
    typeOptions: { rows: 2 },
    default: '',
    displayOptions: showFor('message', ['sendImage', 'sendVideo', 'sendDocument']),
    description: 'Optional caption to accompany the media',
  },
  {
    displayName: 'View Once',
    name: 'viewOnce',
    type: 'boolean',
    default: false,
    displayOptions: showFor('message', ['sendImage', 'sendVideo']),
    description: 'Whether the recipient can only view this media once',
  },
  // Location
  {
    displayName: 'Latitude',
    name: 'latitude',
    type: 'number',
    default: 0,
    required: true,
    displayOptions: showFor('message', ['sendLocation']),
    description: 'Latitude coordinates between -90 and 90',
  },
  {
    displayName: 'Longitude',
    name: 'longitude',
    type: 'number',
    default: 0,
    required: true,
    displayOptions: showFor('message', ['sendLocation']),
    description: 'Longitude coordinates between -180 and 180',
  },
  {
    displayName: 'Location Name',
    name: 'locationName',
    type: 'string',
    default: '',
    displayOptions: showFor('message', ['sendLocation']),
    description: 'Place or venue name (e.g. Eiffel Tower)',
  },
  {
    displayName: 'Location Address',
    name: 'locationAddress',
    type: 'string',
    default: '',
    displayOptions: showFor('message', ['sendLocation']),
    description: 'Street address of the location',
  },
  // Contact
  {
    displayName: 'Contact Full Name',
    name: 'contactName',
    type: 'string',
    default: '',
    required: true,
    displayOptions: showFor('message', ['sendContact']),
    description: 'Display name for the contact card',
  },
  {
    displayName: 'Contact Phone Number',
    name: 'contactPhone',
    type: 'string',
    default: '',
    required: true,
    displayOptions: showFor('message', ['sendContact']),
    description: 'Phone number in international format (e.g. +1234567890)',
  },
  // Poll
  {
    displayName: 'Poll Question',
    name: 'pollQuestion',
    type: 'string',
    default: '',
    required: true,
    displayOptions: showFor('message', ['sendPoll']),
    description: 'The question to ask in the poll',
  },
  createStringListField(
    'Poll Options',
    'pollOptions',
    'e.g. Yes',
    'Provide at least 2 and up to 12 poll options',
    showFor('message', ['sendPoll']),
  ),
  {
    displayName: 'Allow Multiple Answers',
    name: 'pollMultiSelect',
    type: 'boolean',
    default: false,
    displayOptions: showFor('message', ['sendPoll']),
    description: 'Whether voters can select more than one option',
  },
  // Common Options (Mentions, ReplyTo)
  createStringListField(
    'Mentions',
    'mentions',
    'e.g. 1234567890@s.whatsapp.net',
    'Participant JIDs to tag/mention in group chats',
    showFor('message', sendOperations),
  ),
  {
    displayName: 'Reply to Message ID',
    name: 'replyTo',
    type: 'string',
    default: '',
    displayOptions: showFor('message', sendOperations),
    description: 'ID of an earlier message to quote/reply to',
  },
  // Message Management operations
  {
    displayName: 'Message ID',
    name: 'messageId',
    type: 'string',
    default: '',
    required: true,
    displayOptions: showFor('message', ['getInfo', 'markAsRead', 'delete', 'resend']),
    description: 'WhatsApp message ID to inspect, mark read, or delete',
  },
  {
    displayName: 'Chat / Participant JID',
    name: 'chatJid',
    type: 'string',
    default: '',
    displayOptions: showFor('message', ['markAsRead']),
    description: 'Optional chat or sender JID for marking read',
  },
  {
    displayName: 'New Message Text',
    name: 'editText',
    type: 'string',
    typeOptions: { rows: 3 },
    default: '',
    required: true,
    displayOptions: showFor('message', ['edit']),
    description: 'Updated text content for the message',
  },
  {
    displayName: 'Target Message ID',
    name: 'targetMessageId',
    type: 'string',
    default: '',
    required: true,
    displayOptions: showFor('message', ['edit']),
    description: 'The ID of the message to edit',
  },
  // Decrypt media
  {
    displayName: 'Webhook Media Payload (JSON)',
    name: 'decryptPayload',
    type: 'json',
    default: '={{$json.message ?? $json}}',
    required: true,
    displayOptions: showFor('message', ['decryptMedia']),
    description:
      'Pass the incoming webhook message object containing imageMessage, videoMessage, audioMessage, or documentMessage',
  },
  {
    displayName: 'Output Binary Property',
    name: 'binaryPropertyName',
    type: 'string',
    default: 'data',
    required: true,
    displayOptions: showFor('message', ['decryptMedia']),
    description: 'Name of the n8n binary property to store the decrypted or uploaded file',
  },
];
